name: Build EVIL Language Support Extension

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download sources
      uses: actions/checkout@v3
    
    - name: Fetch package info
      uses: nyaa8/package-info@v1.0.0
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.0
      with:
        node-version: '>=20.9.0'
        check-latest: true
        cache: 'npm'
        cache-dependency-path: 'package.json'

    - name: Install VSCE
      run: npm install -g @vscode/vsce

    - name: Pack the extension
      run: vsce pack

    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: 'evil-lang-vscode-${{ env.PACKAGE_VERSION }}.vsix'
        path: 'evil-lang-${{ env.PACKAGE_VERSION }}.vsix'
        if-no-files-found: 'error'
        retention-days: 90
